name: Spec Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  spec-check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod

      - run: go generate ./...

      - name: Spec check README
        run: |
          cd cmd/speccheck
          env CGO_ENABLED=0 go run . -update-readme || true

      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "Update ETSI TS 102 361 specification coverage"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - name: Spec check validation
        run: |
          cd cmd/speccheck
          env CGO_ENABLED=0 go run .
