name: Tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read       # Required for actions/checkout
  checks:   write      # Required for GitHub Checks API

jobs:
  benchmark-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod

      - run: go generate ./...

      - run: CGO_ENABLED=0 go test -C v2 -run ^$ -benchmem -bench=. ./...

  race-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod

      - run: go generate ./...

      - name: Race tests
        run: go test -C v2 ./... -race

  unit-tests:
    uses: ./.github/workflows/unit-test.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  unit-tests-coverage:
    uses: ./.github/workflows/unit-test.yaml
    with:
      coverage: true
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      token: ${{ secrets.GITHUB_TOKEN }}
